Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 4096
  end

  # Currently "ubuntu/bionic64" on VirtualBox requires `type: "virtualbox"`
  # to make synced folder works.
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Add Google Chrome repository
  #config.vm.provision :shell, inline: "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub|sudo apt-key add -"
  #config.vm.provision :shell, inline: "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google.list'"

  # Update repositories
  config.vm.provision :shell, inline: "sudo apt update -y"

  # Upgrade installed packages
  config.vm.provision :shell, inline: "sudo apt upgrade -y"

  # Add desktop environment
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends ubuntu-desktop fonts-ubuntu"
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11"
  # Add `vagrant` to Administrator
  config.vm.provision :shell, inline: "sudo usermod -a -G sudo vagrant"

  # Add Google Chrome
  config.vm.provision :shell, inline: "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb"
  config.vm.provision :shell, inline: "sudo mkdir -p /home/vagrant/.config/google-chrome; sudo cp -rf /vagrant/data/google-chrome/* /home/vagrant/.config/google-chrome; chown -R vagrant.vagrant /home/vagrant/.config/google-chrome"


  # Install nodejs, npm, and gulp
  config.vm.provision :shell, inline: "curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -"
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends nodejs"
  config.vm.provision :shell, inline: "sudo npm install --global gulp-cli"

  # Create PassCert directory and install bitwarden extension (v1.55.0, 8 Dec 2021)
  config.vm.provision :shell, inline: "sudo su - vagrant; cd /home/vagrant; mkdir passcert; cd passcert; git clone https://github.com/bitwarden/browser.git --branch v1.55.0 bw-browser-v1.55; cd bw-browser-v1.55; npm install; npm run build"
  # Clone the memdump-tests repo
  config.vm.provision :shell, inline: "cd /home/vagrant/passcert; git clone https://github.com/passcert-project/memdump-tests"

  # Change permission of new folders
  config.vm.provision :shell, inline: "sudo chown -R vagrant.vagrant /home/vagrant"

  # Install python3-pip, pyautogui, and required packages
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends python3-pip python3-tk python3-dev scrot python3-opencv"
  config.vm.provision :shell, inline: "sudo pip install pyautogui psutil"

  # Install gdb
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends gdb"

  # Restart (Note that the syncedfolder will not be mounted)
  config.vm.provision :shell, inline: "sudo shutdown -r now"
end
