#TODO: Setting up the variables like this at least for now so it's possible to test on other machines
#Might not end up like this but we shall see
INSTALLATION_ID = ""
INSTALLATION_KEY = ""

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 4096
  end

  # Currently "ubuntu/bionic64" on VirtualBox requires `type: "virtualbox"`
  # to make synced folder works.
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Add Google Chrome repository
  #config.vm.provision :shell, inline: "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub|sudo apt-key add -"
  #config.vm.provision :shell, inline: "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google.list'"

  # Update repositories
  config.vm.provision :shell, inline: "sudo apt update -y"

  # Upgrade installed packages
  config.vm.provision :shell, inline: "sudo apt upgrade -y"

  # Add desktop environment
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends ubuntu-desktop fonts-ubuntu"
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11"
  # Add `vagrant` to Administrator
  config.vm.provision :shell, inline: "sudo usermod -a -G sudo vagrant"

  # Add Google Chrome
  config.vm.provision :shell, inline: "wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_99.0.4844.51-1_amd64.deb"
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends ./google-chrome-stable_99.0.4844.51-1_amd64.deb"
  config.vm.provision :shell, inline: "sudo mkdir -p /home/vagrant/.config/google-chrome; sudo cp -rf /vagrant/data/google-chrome/* /home/vagrant/.config/google-chrome; chown -R vagrant.vagrant /home/vagrant/.config/google-chrome"
 
  # Install nodejs, npm, and gulp
  config.vm.provision :shell, inline: "curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -"
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends nodejs"
  config.vm.provision :shell, inline: "sudo npm install --global gulp-cli"

  # Create PassCert directory and install bitwarden extension (v1.55.0, 8 Dec 2021)
  config.vm.provision :shell, inline: "sudo su - vagrant; cd /home/vagrant; mkdir passcert; cd passcert; git clone https://github.com/bitwarden/browser.git --branch v1.55.0 bw-browser-v1.55; cd bw-browser-v1.55; npm install; npm run build"
  
  #Create directories for the PassCert BitWarden extensions
  config.vm.provision :shell, inline: "sudo su - vagrant; cd /home/vagrant/passcert; git clone https://github.com/squeakyrino/browser.git --branch arraybuffer-experiment bw-browser-child-component; cd bw-browser-child-component; npm install; npm run build"
  config.vm.provision :shell, inline: "sudo su - vagrant; cd /home/vagrant/passcert; git clone https://github.com/squeakyrino/browser.git --branch ArrayBuffer-No-Child-Component bw-browser-no-child-component; cd bw-browser-no-child-component; npm install; npm run build"
  
  # Clone the memdump-tests repo
  config.vm.provision :shell, inline: "cd /home/vagrant/passcert; git clone https://github.com/passcert-project/memdump-tests"

  # Change permission of new folders
  config.vm.provision :shell, inline: "sudo chown -R vagrant.vagrant /home/vagrant"

  # Install python3-pip, pyautogui, and required packages
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends python3-pip python3-tk python3-dev scrot python3-opencv"
  config.vm.provision :shell, inline: "sudo pip install pyautogui psutil natsort tqdm"

  # Install gdb
  config.vm.provision :shell, inline: "sudo apt install -y --no-install-recommends gdb"

  # BitWarden local server
  # Install containerd.io (necessary for Docker Engine)
  config.vm.provision :shell, inline: "cd /home/vagrant; wget https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.4.9-1_amd64.deb"
  config.vm.provision :shell, inline: "sudo dpkg -i containerd.io_1.4.9-1_amd64.deb"

  # Install Docker Engine (ce and ce-cli)
  config.vm.provision :shell, inline: "wget https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb"
  config.vm.provision :shell, inline: "sudo dpkg -i docker-ce-cli_20.10.9~3-0~ubuntu-focal_amd64.deb"
  config.vm.provision :shell, inline: "wget https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb"
  config.vm.provision :shell, inline: "sudo dpkg -i docker-ce_20.10.9~3-0~ubuntu-focal_amd64.deb"

  # Install Docker Compose
  config.vm.provision :shell, inline: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
  config.vm.provision :shell, inline: "sudo chmod +x /usr/local/bin/docker-compose"

  # Installing BitWarden local server
  config.vm.provision :shell, inline: "sudo mkdir -p /home/vagrant/BitWardenServer; cd /home/vagrant/BitWardenServer;sudo curl -Lso bitwarden.sh https://go.btwrdn.co/bw-sh && sudo chmod 700 bitwarden.sh"

  # Install expect
  config.vm.provision :shell, inline: "sudo apt-get install -y --no-install-recommends expect"
  
  # Copy the expect script over to the VM
  config.vm.provision :shell, inline: "sudo cp -rf /vagrant/BitWardenServerScript.exp /home/vagrant/BitWardenServer; sudo chown -R vagrant.vagrant /home/vagrant/BitWardenServer"

  # Run the expect script provided with the id and key given
  config.vm.provision "shell" do |s|
    s.inline = "sudo /home/vagrant/BitWardenServer/BitWardenServerScript.exp $1 $2"
    s.args = [INSTALLATION_ID, INSTALLATION_KEY]
  end

  # Start the BitWarden server
  config.vm.provision :shell, inline: "sudo /home/vagrant/BitWardenServer/bitwarden.sh start"

  # Tell linux to accept the stupid ass certificate since the generation is already handled by bitwarden
  #https://bitwarden.com/help/certificates/#using-a-self-signed-certificate
  
  
  # Restart (Note that the syncedfolder will not be mounted)
  config.vm.provision :shell, inline: "sudo shutdown -r now"
end
